name: KIT_PLAYER
description: "A multimedia player application with video and audio support"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.8.1

# التبعيات المطلوبة لتطبيق UI Kit
dependencies:
  # Flutter SDK الأساسي
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  
  # إدارة الحالة والتفضيلات
  provider: ^6.1.2             # إدارة الحالة
  shared_preferences: ^2.3.2   # التفضيلات المحفوظة
  
  # واجهة المستخدم والتصميم
  clay_containers: ^0.3.2      # تأثيرات Neumorphic
  

# أدوات التطوير والاختبار
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # أدوات جودة الكود
  flutter_lints: ^5.0.0        # قواعد جودة الكود
  
  # أدوات البناء والإعداد
  build_runner: ^2.6.0         # بناء الملفات المتولدة
  flutter_launcher_icons: ^0.14.1  # إعداد أيقونات التطبيق

# إعدادات Flutter
flutter:
  uses-material-design: true  # استخدام Material Design

  # موارد التطبيق
  assets:
    - assets/icons/       # أيقونات التطبيق
    - assets/images/      # صور التطبيق
    - assets/audio/       # ملفات صوتية افتراضية
    
  # الخطوط المخصصة (يمكن إضافة خطوط عربية)
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Regular.ttf
  #       - asset: assets/fonts/Cairo-Bold.ttf
  #         weight: 700
  #   - family: Amiri
  #     fonts:
  #       - asset: assets/fonts/Amiri-Regular.ttf
  #       - asset: assets/fonts/Amiri-Bold.ttf
  #         weight: 700

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#000000"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"
